export const ActionConsts = {
  Common: {
    SET_IS_LOADING: "SET_IS_LOADING",
    RESET_REDUCER: "RESET_REDUCER",
  },
  Dashboard: {
    SET_USERS: "SET_USERS",
    RESET_REDUCER: "RESET_REDUCER",
  },
  Settings: {
    CREATE_NEW_USER: "CREATE_NEW_USER",
    UPDATE_NEW_USER: "UPDATE_NEW_USER",
    DELETE_NEW_USER: "DELETE_NEW_USER",
    RESET_REDUCER: "RESET_REDUCER",
  },
};
